version: '3.2'

networks:
  pre-event-network:
    driver: bridge

services:
  #Service-tuition
  pre-service-tuition:
    container_name: pre-service-tuition
    build:
      context: ../service-tuition/.
      dockerfile: ../service-tuition/Dockerfile
    ports:
      - "1223:1223"
    networks:
      - pre-event-network
    depends_on:
      - pre-redis
    environment:
      - SPRING_PROFILES_ACTIVE=local
  #Service-register
  pre-service-register:
    container_name: pre-service-register
    build:
      context: ../service-register/.
      dockerfile: ../service-register/Dockerfile
    ports:
      - "1222:1222"
    networks:
      - pre-event-network
    depends_on:
      - pre-redis
    environment:
      - SPRING_PROFILES_ACTIVE=local
  #Redis
  pre-redis:
    container_name: pre-redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - pre-event-network
  #Prometheus
  pre-prometheus:
    container_name: pre-prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - pre-event-network
  #Node Exporter
  pre-node-exporter:
    container_name: pre-node-exporter
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    networks:
      - pre-event-network
  #Grafana
  pre-grafana:
    container_name: pre-grafana
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Set the admin password (default: admin)
      - GF_DASHBOARDS_JSON_ENABLED=true  # Enable the loading of dashboards from JSON files
    volumes:
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
    ports:
      - "3000:3000"
    networks:
      - pre-event-network