version: '3.2'

networks:
  pre-event-network:
    driver: bridge

services:
  #Service-register
  service-register:
    container_name: service-register
    build:
      context: ../service-register/.
      dockerfile: ../service-register/Dockerfile
    ports:
      - "1222:1222"
    networks:
      - pre-event-network
    depends_on:
      - redis
  #Redis
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - pre-event-network
  #Prometheus
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - pre-event-network
  #Node Exporter
  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    networks:
      - pre-event-network
  #Grafana
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Set the admin password (default: admin)
      - GF_DASHBOARDS_JSON_ENABLED=true  # Enable the loading of dashboards from JSON files
    volumes:
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards  # Mount dashboards folder
    ports:
      - "3000:3000"
    networks:
      - pre-event-network